name: Deploy Hexo Blog

on:
  push:
    branches:
      - hexo  # 当推送到 hexo 分支时触发

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: 安装依赖
      run: |
        npm install
        npm install hexo-cli -g
    
    - name: 生成静态文件
      run: |
        hexo clean
        hexo generate
    
    - name: 部署到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: main
        force_orphan: true
