# name: Deploy Hexo Blog

# on:
#   push:
#     branches:
#       - hexo  # 当推送到 hexo 分支时触发

# permissions:
#   contents: write

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: 检出代码
#       uses: actions/checkout@v3
#       with:
#         submodules: true
#         fetch-depth: 0
    
#     - name: 设置 Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'
    
#     - name: 安装依赖
#       run: |
#         npm install
#         npm install hexo-cli -g
    
#     - name: 生成静态文件
#       run: |
#         hexo clean
#         hexo generate
    
#     - name: 部署到 GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./public
#         publish_branch: main
#         force_orphan: true

name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Configuration environment
        env:
          ID_RSA: ${{secrets.id_rsa}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name '<atm2086>'
          git config --global user.email '<1534856536@qq.com>'
      
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      
      - name: Deploy hexo
        run: |
          hexo g -d